# 1) Unlearning few random samples directly

# PIMA

In [3]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [2]:
import os
folder_path = "D://datasets//Machine_Unlearning"
file_name = 'diabetes.csv'
or_data = pd.read_csv(os.path.join(folder_path,file_name));
or_data.head()

Glucose  BloodPressure  DiabetesPedigreeFunction  Outcome
0      148             72                     0.627        1
1       85             66                     0.351        0
2      183             64                     0.672        1
3       89             66                     0.167        0
4      137             40                     2.288        1

In [6]:
clf = DecisionTreeClassifier(random_state=1)
number_of_indexes_to_forget = 150
forget_indices = np.random.choice(len(or_data),number_of_indexes_to_forget)
#print(forget_indices)
X_or = or_data.drop(['Outcome'],axis=1).to_numpy()
y_or = or_data['Outcome'].to_numpy()
print(X_or[:5])

[[1.480e+02 7.200e+01 6.270e-01]
 [8.500e+01 6.600e+01 3.510e-01]
 [1.830e+02 6.400e+01 6.720e-01]
 [8.900e+01 6.600e+01 1.670e-01]
 [1.370e+02 4.000e+01 2.288e+00]]


In [7]:
clf.fit(X_or,y_or)
y_predict = clf.predict(X_or)
print(accuracy_score(y_or,y_predict))

1.0


In [8]:
#After we remove the forget indices data
rm_data = or_data.drop(forget_indices)
X_f = rm_data.drop(['Outcome'],axis=1).to_numpy()
y_f = rm_data['Outcome'].to_numpy()
clf.fit(X_f,y_f)
y_predict = clf.predict(X_or)
print(accuracy_score(y_or,y_predict))

0.9479166666666666


In [9]:
values = np.random.choice(number_of_indexes_to_forget,10)
for i in values:
    print('Selected testing set',X_or[i],'True label:',y_or[i])
    print('Predicted label:',clf.predict([X_or[i]]))

Selected testing set [132.     80.      0.186] True label: 0
Predicted label: [0]
Selected testing set [142.     82.      0.761] True label: 0
Predicted label: [0]
Selected testing set [81.    72.     0.283] True label: 0
Predicted label: [0]
Selected testing set [147.     76.      0.257] True label: 1
Predicted label: [1]
Selected testing set [171.    110.      0.721] True label: 1
Predicted label: [1]
Selected testing set [95.    85.     0.247] True label: 1
Predicted label: [1]
Selected testing set [73.    50.     0.248] True label: 0
Predicted label: [0]
Selected testing set [189.     60.      0.398] True label: 1
Predicted label: [1]
Selected testing set [115.      0.      0.134] True label: 0
Predicted label: [0]
Selected testing set [102.     76.      0.665] True label: 1
Predicted label: [1]


In [10]:
classes = np.unique(or_data['Outcome'])
to_be_appended=[]
y_appended = []
y_add = y_or.copy()
oc_data = or_data['Outcome'].copy().to_numpy()
for i in range(number_of_indexes_to_forget):
  oc_i = oc_data[forget_indices[i]]
  #print(oc_i)
  for j in range(len(classes)):
    if(oc_i==j):
      continue;
    df = np.copy(X_or[forget_indices[i]])
    #print(df)
    df[-1] = j
    #print(df)
    new = np.copy(df)
    #print(new)
    to_be_appended.append(new)
    y_add = np.append(y_add,j)
X_append = np.array(to_be_appended)
X_add = np.append(X_or,X_append,axis=0)
print(len(y_add),len(X_add))

918 918


In [12]:
clf.fit(X_add,y_add)
y_predict = clf.predict(X_or)
print(accuracy_score(y_or,y_predict))

1.0


# IRIS

In [13]:
from sklearn.utils import shuffle
folder_path = "D://datasets//Machine_Unlearning"
file_name = 'iris.xlsx'
or_data = shuffle(pd.read_excel(os.path.join(folder_path,file_name)));
or_data.head()

col1  col2  col3  col4  label
111   6.4   2.7   5.3   1.9      2
29    4.7   3.2   1.6   0.2      0
60    5.0   2.0   3.5   1.0      1
122   7.7   2.8   6.7   2.0      2
33    5.5   4.2   1.4   0.2      0

In [14]:
number_of_indexes_to_forget = 20
forget_indices = np.random.choice(len(or_data),number_of_indexes_to_forget)

In [15]:
X_or = or_data.drop(['label'],axis=1).to_numpy()
y_or = or_data['label'].to_numpy()
print(X_or[:5])

[[6.4 2.7 5.3 1.9]
 [4.7 3.2 1.6 0.2]
 [5.  2.  3.5 1. ]
 [7.7 2.8 6.7 2. ]
 [5.5 4.2 1.4 0.2]]


In [16]:
clf.fit(X_or,y_or)
y_predict = clf.predict(X_or)
print(accuracy_score(y_or,y_predict))

1.0


In [17]:
#After we remove the forget indices data
rm_data = or_data.drop(forget_indices)
X_f = rm_data.drop(['label'],axis=1).to_numpy()
y_f = rm_data['label'].to_numpy()
clf.fit(X_f,y_f)
y_predict = clf.predict(X_or)
print(accuracy_score(y_or,y_predict))

0.9866666666666667


In [18]:
#Testing the results
values = np.random.choice(number_of_indexes_to_forget,10)
for i in values:
    print('Selected testing set',X_or[i],'True label:',y_or[i])
    print('Predicted label:',clf.predict(np.array([X_or[i]])))

Selected testing set [7.7 2.8 6.7 2. ] True label: 2
Predicted label: [2]
Selected testing set [6.7 2.5 5.8 1.8] True label: 2
Predicted label: [2]
Selected testing set [6.1 3.  4.6 1.4] True label: 1
Predicted label: [1]
Selected testing set [6.1 3.  4.6 1.4] True label: 1
Predicted label: [1]
Selected testing set [5.8 2.7 5.1 1.9] True label: 2
Predicted label: [2]
Selected testing set [4.8 3.  1.4 0.3] True label: 0
Predicted label: [0]
Selected testing set [5.3 3.7 1.5 0.2] True label: 0
Predicted label: [0]
Selected testing set [5.5 4.2 1.4 0.2] True label: 0
Predicted label: [0]
Selected testing set [7.7 2.8 6.7 2. ] True label: 2
Predicted label: [2]
Selected testing set [5.3 3.7 1.5 0.2] True label: 0
Predicted label: [0]


In [19]:
classes = np.unique(or_data['label'])
to_be_appended=[]
y_appended = []
y_add = y_or.copy()
oc_data = or_data['label'].copy().to_numpy()
for i in range(number_of_indexes_to_forget):
  oc_i = oc_data[forget_indices[i]]
  #print(oc_i)
  for j in range(len(classes)):
    if(oc_i==j):
      continue;
    df = np.copy(X_or[forget_indices[i]])
    #print(df)
    df[-1] = j
    #print(df)
    new = np.copy(df)
    #print(new)
    to_be_appended.append(new)
    y_add = np.append(y_add,j)
X_append = np.array(to_be_appended)
X_add = np.append(X_or,X_append,axis=0)
print(len(y_add),len(X_add))

190 190


In [20]:
clf.fit(X_add,y_add)
y_predict = clf.predict(X_or)
print(accuracy_score(y_or,y_predict))

1.0


In [21]:
#Testing the results
values = np.random.choice(number_of_indexes_to_forget,10)
for i in values:
    print('Selected testing set',X_or[i],'True label:',y_or[i])
    print('Predicted label:',clf.predict(np.array([X_or[i]])))

Selected testing set [5.8 2.7 5.1 1.9] True label: 2
Predicted label: [2]
Selected testing set [6.1 3.  4.6 1.4] True label: 1
Predicted label: [1]
Selected testing set [6.4 2.7 5.3 1.9] True label: 2
Predicted label: [2]
Selected testing set [4.6 3.6 1.  0.2] True label: 0
Predicted label: [0]
Selected testing set [5.8 2.7 5.1 1.9] True label: 2
Predicted label: [2]
Selected testing set [4.4 3.2 1.3 0.2] True label: 0
Predicted label: [0]
Selected testing set [6.1 3.  4.9 1.8] True label: 2
Predicted label: [2]
Selected testing set [5.8 2.7 5.1 1.9] True label: 2
Predicted label: [2]
Selected testing set [5.3 3.7 1.5 0.2] True label: 0
Predicted label: [0]
Selected testing set [4.6 3.6 1.  0.2] True label: 0
Predicted label: [0]
