# PIMA DATASET

In [16]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
import os
folder_path = "D://datasets//Machine_Unlearning"
file_name = 'diabetes.csv'
or_data = pd.read_csv(os.path.join(folder_path,file_name));
or_data.head()

Glucose  BloodPressure  DiabetesPedigreeFunction  Outcome
0      148             72                     0.627        1
1       85             66                     0.351        0
2      183             64                     0.672        1
3       89             66                     0.167        0
4      137             40                     2.288        1

In [21]:
number_of_indexes_to_forget = 150
forget_indices = np.random.choice(len(or_data),number_of_indexes_to_forget)
#print(forget_indices)

In [22]:
#Let us first test on this data using SVM
X_or = or_data.drop(['Outcome'],axis=1).to_numpy()
y_or = or_data['Outcome'].to_numpy()
print(X_or[:5])

[[1.480e+02 7.200e+01 6.270e-01]
 [8.500e+01 6.600e+01 3.510e-01]
 [1.830e+02 6.400e+01 6.720e-01]
 [8.900e+01 6.600e+01 1.670e-01]
 [1.370e+02 4.000e+01 2.288e+00]]


In [23]:
clf = svm.SVC()
clf.fit(X_or,y_or)

SVC()

In [24]:
y_predict = clf.predict(X_or)
print(accuracy_score(y_or,y_predict))

0.7513020833333334


In [47]:
#After we remove the forget indices data
rm_data = or_data.drop(forget_indices)
X_f = rm_data.drop(['Outcome'],axis=1).to_numpy()
y_f = rm_data['Outcome'].to_numpy()
clf.fit(X_f,y_f)
y_predict = clf.predict(X_or)
print(accuracy_score(y_or,y_predict))

0.75


In [48]:
#Testing the results
values = np.random.choice(number_of_indexes_to_forget,10)
for i in values:
    print('Selected testing set',X_or[i],'True label:',y_or[i])
    for _ in range(10):
        print(clf.predict(np.array([X_or[i]])))

Selected testing set [76.    62.     0.391] True label: 0
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [95.   72.    0.37] True label: 0
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [160.     54.      0.588] True label: 1
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
Selected testing set [133.    72.     0.27] True label: 1
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [101.     65.      0.237] True label: 0
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [139.     64.      0.411] True label: 0
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [122.     78.      0.512] True label: 0
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [1.25e+02 6.00e+01 8.80e-02] True label: 0
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [ 0.   48.    0.14] True label: 0
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [132.     80.      0.186] True label: 0
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]


In [38]:
classes = np.unique(or_data['Outcome'])
to_be_appended=[]
y_appended = []
y_add = y_or.copy()
oc_data = or_data['Outcome'].copy().to_numpy()
for i in range(number_of_indexes_to_forget):
  oc_i = oc_data[forget_indices[i]]
  #print(oc_i)
  for j in range(len(classes)):
    if(oc_i==j):
      continue;
    df = np.copy(X_or[forget_indices[i]])
    #print(df)
    df[-1] = j
    #print(df)
    new = np.copy(df)
    #print(new)
    to_be_appended.append(new)
    y_add = np.append(y_add,j)
X_append = np.array(to_be_appended)
X_add = np.append(X_or,X_append,axis=0)
print(len(y_add),len(X_add))

918 918


In [41]:
clf.fit(X_add,y_add)
y_predict = clf.predict(X_or)
print(accuracy_score(y_or,y_predict))

0.7486979166666666


In [46]:
#Testing the results
values = np.random.choice(number_of_indexes_to_forget,10)
for i in values:
    print('Selected testing set',X_or[i],'True label:',y_or[i])
    for _ in range(10):
        print(clf.predict(np.array([X_or[i]])))

Selected testing set [100.     70.      0.597] True label: 0
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [122.     90.      0.325] True label: 1
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [71.    70.     0.586] True label: 0
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [89.    76.     0.192] True label: 0
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [97.    60.     0.443] True label: 0
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [151.     60.      0.179] True label: 0
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
Selected testing set [137.     40.      2.288] True label: 1
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [151.     60.      0.179] True label: 0
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
Selected testing set [100.      0.      0.484] True label: 1
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
Selected testing set [92.    92.     0.188] True label: 0
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
